# Generated by Django 5.0.6 on 2024-06-26 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='developer',
            old_name='rate',
            new_name='grade',
        ),
        migrations.AlterField(
            model_name='deliverymanager',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_manager', to='user.customer'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='delivery_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='developers', to='user.deliverymanager'),
        ),
    ]
